<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <AssemblyName>MakuTweaker</AssemblyName>
    <Authors>MarkAdderly</Authors>
    <Version>5.8.7</Version>
    <PackageIcon>MakuTweakerNEWnoround.png</PackageIcon>
    <PackageProjectUrl>https://adderly.top</PackageProjectUrl>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  <TargetPlatformVersion>10.0</TargetPlatformVersion>
	  <ApplicationIcon>assets/icons/MakuTweaker.ico</ApplicationIcon>
	  <PlatformTarget>x64</PlatformTarget>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <FileVersion>5.8.7</FileVersion>
    <AssemblyVersion>5.8.7</AssemblyVersion>
    <Title>MakuTweaker</Title>
    <Copyright>MarkAdderly</Copyright>
    <PackageTags>makutweaker</PackageTags>
    <RepositoryUrl>https://github.com/MarkAdderly/MakuTweaker</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\icons\MakuT.ico" />
    <None Remove="BuildNumber.txt" />
    <None Remove="assets/images/hand_heart_donate_icon.png" />
    <None Remove="assets/images/makut.png" />
    <None Remove="assets/images/MakuTweakerAbout.png" />
    <None Remove="assets/images/Telegram_2019_Logo.svg.png" />
    <None Remove="assets/images/You-Tube-16.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="loc\*.json" />
    <Content Include="assets/icons/MakuTweaker.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="BuildNumber.txt" />
    <Resource Include="assets/images/hand_heart_donate_icon.png" />
    <Resource Include="assets/images/makut.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
    <PackageReference Include="MicaWPF" Version="6.2.10" />
    <PackageReference Include="ModernWpf.MessageBox.Mica" Version="0.5.5" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NvAPIWrapper.Net" Version="0.8.1.101" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.8" />
    <PackageReference Include="System.Management" Version="9.0.9" />
    <PackageReference Include="Vortice.DirectX" Version="3.6.2" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
    <PackageReference Include="Vortice.Win32.Graphics.Dxgi" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets/images/MakuTweakerAbout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets/images/Telegram_2019_Logo.svg.png" />
    <Resource Include="assets/images/You-Tube-16.png" />
    <Resource Include="assets\icons\MakuT.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SiteBan.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="MakuYan.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="HidePart.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="WinInfo.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Perf.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="SettingsAbout.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PCI.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Advanced.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UWP.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Act.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="SysAndRec.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="AppInstal.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="QuickSet.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="SAT.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Personalization.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ProcessMGR.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="WindowsUpdate.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="WindowsComponents.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="MakuTweakerNEWnoround.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="SAT.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="WindowsUpdate.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>


	<Target Name="UpdateBuildInfo" BeforeTargets="BeforeBuild">
		<Exec Command="powershell -File &quot;$(MSBuildProjectDirectory)\UpdateBuildNumber.ps1&quot;" />
	</Target>

<Target Name="RemoveOnlyLanguageFolders" AfterTargets="Build">
    <ItemGroup>
      <LangDirs Include="$(OutputPath)*\" Condition="Exists('%(Identity)') &#xD;&#xA;                           AND '%(Filename)' != 'en' &#xD;&#xA;                           AND '%(Filename)' != 'en-US' &#xD;&#xA;                           AND $([System.Text.RegularExpressions.Regex]::IsMatch('%(Filename)', '^[a-z]{2}(-[A-Z]{2})?$'))" />
    </ItemGroup>
    <RemoveDir Directories="@(LangDirs)" />
  </Target>

  <Target Name="RemoveOnlyLanguageFoldersAfterPublish" AfterTargets="Publish">
    <ItemGroup>
      <LangDirs Include="$(PublishDir)*\" Condition="Exists('%(Identity)') &#xD;&#xA;                           AND '%(Filename)' != 'en' &#xD;&#xA;                           AND '%(Filename)' != 'en-US' &#xD;&#xA;                           AND $([System.Text.RegularExpressions.Regex]::IsMatch('%(Filename)', '^[a-z]{2}(-[A-Z]{2})?$'))" />
    </ItemGroup>
    <RemoveDir Directories="@(LangDirs)" />
  </Target>

</Project>
